title:       Streamdata Gallery
url:         http://template.streamdata.gallery
raw_url: https://raw.githubusercontent.com/api-stack/market-data/master/_data/api-commons/
tag: Market Data
logo:        https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-logo-market-data.png
version:     1.1.1
markdown:    kramdown
permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
paginate: 25
paginate_path: "/blog/page:num"
github_user: streamdata-gallery
github_repo: apis
github_branch: master

collections:
  gallery:
    output: true
    permalink: /gallery/:path/

defaults:
  - scope:
      type: gallery
    values:
      layout: gallery
