title:        Market Data APIs
url:          http://market.data.apievangelist.com
raw_url: https://raw.githubusercontent.com/api-stack/market-data/master/_data/api-commons/

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

github_user: api-stack
github_repo: market-data
github_branch: master
