title:       Streamdata Gallery
url:         http://template.streamdata.gallery

raw_url: https://raw.githubusercontent.com/api-stack/market-data/master/_data/api-commons/

tag: Market Data

version:     1.1.1
markdown:    kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

github_user: streamdata-gallery
github_repo: template
github_branch: master

collections:
  links:
    output: true
    permalink: /links/:path/
    label: Links

defaults:
  - scope:
      type: links
    values:
      layout: links
